cudnn_benchmark: true
device: cpu
model:
  drop_connect_rate: 0.2
  name: EfficientNet
  num_classes: 101
  scaler:
    alpha: 1.2
    beta: 1.1
    gamma: 1.15
    phi: 0
training:
  base_batch_size: 64
  optimizer:
    alpha: 0.9
    eps: 0.001
    lr: 0.064
    momentum: 0.9
    type: RMSprop
    weight_decay: 1.0e-05
  scheduler:
    gamma_per_epoch: 0.9873888589377785
    type: ExponentialLR
