cudnn_benchmark: true
device: cuda_if_available

model:
  name: EfficientNet
  num_classes: 30
  drop_connect_rate: 0.2
  scaler:
    alpha: 1.2
    beta: 1.1
    gamma: 1.15
    phi: 0

training:
  base_batch_size: 64
  optimizer:
    type: AdamW
    lr: 1.0e-3
    weight_decay: 1.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-8
  scheduler:
    type: OneCycleLR
    max_lr: 1.0e-3
    epochs: 30
    steps_per_epoch: len(train_loader)
    pct_start: 0.1
    div_factor: 10.0
    final_div_factor: 1.0e3
    cycle_momentum: false
