device: cuda   # o cpu, se ajusta autom√°ticamente en el script

model:
  name: ResNet50
  num_classes: 10
  first_block: conv

criterion:
  name: CrossEntropyLoss

optimizer:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001

training:
  epochs: 10
  mixed_precision: false
